# Python Data Manuplation Pandas

In [15]:
import pandas as  pd

In [16]:
seri = pd.Series([10,28,34,46,5,3,90,75])
seri

0    10
1    28
2    34
3    46
4     5
5     3
6    90
7    75
dtype: int64

In [17]:
type(seri)

pandas.core.series.Series

In [18]:
seri.axes

[RangeIndex(start=0, stop=8, step=1)]

In [19]:
seri.dtype

dtype('int64')

In [20]:
seri.size

8

In [21]:
seri.ndim

1

In [22]:
seri.shape

(8,)

In [23]:
seri.values

array([10, 28, 34, 46,  5,  3, 90, 75], dtype=int64)

In [24]:
seri.head()

0    10
1    28
2    34
3    46
4     5
dtype: int64

In [26]:
seri.tail()

3    46
4     5
5     3
6    90
7    75
dtype: int64

In [27]:
#Index isimlendirmesi

In [33]:
seri = pd.Series([1,2,3,4,5] , index=["a","b","c","d","e"]) #index=[] ile isimlendirme yapılabilir
seri

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [34]:
seri["a"] 

1

In [35]:
seri["a":"c"]

a    1
b    2
c    3
dtype: int64

In [36]:
#Sozluk üzerinden liste olusturmak

In [38]:
dic = pd.Series({"a":1,"b":2,"c":3})
dic

a    1
b    2
c    3
dtype: int64

In [39]:
dic["a"]

1

In [41]:
#Iki seriyi birlestirerek seri olusturmak

seri1 = pd.Series([1,2,3])
seri2 = pd.Series([3,4,5])

pd.concat([seri1,seri2])

0    1
1    2
2    3
0    3
1    4
2    5
dtype: int64

## Eleman islemleri

In [46]:
import numpy as np
import pandas as pd

np_array = np.array([56,45,88,29])
pd_seri = pd.Series(np_array)
pd_seri

0    56
1    45
2    88
3    29
dtype: int32

In [47]:
pd_seri[1:3]

1    45
2    88
dtype: int32

In [49]:
seri = pd.Series([100,200,300],index=("a","b","c"))
seri

a    100
b    200
c    300
dtype: int64

In [50]:
seri.index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
seri.keys

<bound method Series.keys of a    100
b    200
c    300
dtype: int64>

In [52]:
list(seri.items())

[('a', 100), ('b', 200), ('c', 300)]

In [53]:
seri.values

array([100, 200, 300], dtype=int64)

In [54]:
#Eleman sorgulama

In [55]:
"a" in seri

True

In [56]:
"d" in seri

False

In [57]:
#Fancy ile eleman secme islemi

In [59]:
seri[["a","b"]]

a    100
b    200
dtype: int64

In [60]:
seri["a"]

100

In [62]:
seri["a"] = 276
seri["a"]

276

## Pandas DataFrame Olusturmak

In [63]:
import pandas as pd

In [64]:
pd_list = [45,34,76,32,98]
pd_list

[45, 34, 76, 32, 98]

In [66]:
pd.DataFrame(pd_list , columns=["column_name"])

column_name
0           45
1           34
2           76
3           32
4           98

In [67]:
import numpy as np

In [73]:
list2dim = np.random.randint(9,size=(3,3))
list2dim

array([[4, 7, 7],
       [6, 6, 1],
       [0, 2, 5]])

In [74]:
pd.DataFrame(list2dim , columns=["column1","column2","column3"])

column1  column2  column3
0        4        7        7
1        6        6        1
2        0        2        5

In [75]:
#Data Frame isimlendirme

In [77]:
df = pd.DataFrame(list2dim , columns=["column1","column2","column3"])
df

column1  column2  column3
0        4        7        7
1        6        6        1
2        0        2        5

In [78]:
df.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [81]:
df.columns = ("a","b","c")
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [82]:
df.values

array([[4, 7, 7],
       [6, 6, 1],
       [0, 2, 5]])

In [83]:
type(df.values)

numpy.ndarray

In [84]:
df.head()

a  b  c
0  4  7  7
1  6  6  1
2  0  2  5

In [85]:
df.tail(1)

a  b  c
2  0  2  5

## Eleman Islemleri

In [93]:

import numpy as np
import pandas as pd

a = np.random.randint(20, size=(4,5))
a


array([[19,  1,  0,  4, 13],
       [ 2, 18,  3, 11,  1],
       [12, 10,  4, 10,  0],
       [19, 11, 19,  8,  5]])

In [94]:
a_pd = pd.DataFrame(a , columns=["var0","var1","var2","var3","var4"])
a_pd

var0  var1  var2  var3  var4
0    19     1     0     4    13
1     2    18     3    11     1
2    12    10     4    10     0
3    19    11    19     8     5

In [95]:
a_pd.index

RangeIndex(start=0, stop=4, step=1)

In [98]:
a_pd.index= ["a","b","c","d"]
a_pd

var0  var1  var2  var3  var4
a    19     1     0     4    13
b     2    18     3    11     1
c    12    10     4    10     0
d    19    11    19     8     5

In [99]:
#Eleman Silme
a_pd.drop("a" , axis = 0) #Kalıcı Silme islemi yapmaz.

var0  var1  var2  var3  var4
b     2    18     3    11     1
c    12    10     4    10     0
d    19    11    19     8     5

In [105]:
a_pd

var0  var1  var2  var3  var4
b     2    18     3    11     1
c    12    10     4    10     0
d    19    11    19     8     5

In [106]:
a_pd.drop("b",axis=0,inplace = True) #inplace=True kalici silme islemi yapar

In [107]:
a_pd

var0  var1  var2  var3  var4
c    12    10     4    10     0
d    19    11    19     8     5

In [110]:
a_pd.drop("var1",axis=1) #axis=1 sutun , axis=0 satiri temsil eder


var0  var2  var3  var4
c    12     4    10     0
d    19    19     8     5