# Data Manuplation NumPy & Pandas

In [1]:

import numpy as np

newarray = np.array([1,2,3,4,5])
newarray

array([1, 2, 3, 4, 5])

In [2]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a*b

array([ 2,  6, 12])

In [3]:
type(newarray)

numpy.ndarray

In [4]:
np.zeros(10,dtype=int) # dtype elemanlarin turunu belirtmek icin kullanilir

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Creating NumPy Array

In [7]:
import numpy as np

np.arange(0,30,3) # tek boyutlu dizi olusturma (0 dan 30 a kadar 3 er artan)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
np.linspace(0,1,10) # Iki deger araliginda sayilar olusturur (0 ve 1 arasinda 10 sayi olusturur)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.random.normal(10,4,(3,4)) # Normal dagilima uygun array olusturur (ort: 10 , standart sapma:4 , 3 e 4 luk array)

array([[11.99081994, 13.90281501,  8.00427561,  6.21600601],
       [10.87238912,  7.5286911 , 10.90486082, 13.98390575],
       [10.97905479, 11.31335827,  8.01076911,  4.98267217]])

In [10]:
np.random.randint(0,10,(3,3)) # rastgele int ler olusturmak (0 dan 10 a kadar 3'e 3 luk)

array([[6, 2, 8],
       [7, 6, 3],
       [2, 5, 5]])

### Numpy Array Ozellikleri
* ndim : boyut sayisi
* shape : boyut bilgisi
* size : toplam eleman sayisi
* dtype : Array veri tipi

In [11]:
import numpy as np

array = np.arange(16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
array.ndim

1

In [13]:
array.shape

(16,)

In [14]:
array.size

16

In [15]:
array.dtype

dtype('int32')

In [16]:
array2 = np.random.randint(0,10,(3,3))
array2

array([[1, 8, 8],
       [4, 0, 1],
       [0, 6, 0]])

In [17]:
array2.ndim

2

In [18]:
array2.shape

(3, 3)

In [19]:
array2.size

9

In [20]:
array2.dtype

dtype('int32')

#### Reshaping (Yeniden Sekillendirme)

In [21]:
array = np.arange(30)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array.reshape(5,6) # Tek yonlu array'i (vector) 5'e 6 lik hale getirdik (matrix).

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### Concatenation (Array Birlestirme)

In [11]:
import numpy as np

a = np.random.randint(0,10, size=5)
a

array([7, 2, 7, 6, 2])

In [12]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [14]:
ab = np.concatenate([a,b]) # concatenate() array birlestirmek icin kullanilir
ab

array([7, 2, 7, 6, 2, 0, 1, 2, 3, 4])

In [16]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[2,2,2]])

xy = np.concatenate([x,y])
xy

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [18]:
cy = np.concatenate([x,y], axis = 1) # axis degeri sutuna mi satira mi ekleneceğini belirtir.
cy

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

## Splitting (Array Ayirma)

In [19]:
import numpy as np

In [20]:
x = np.array([1,2,3,99,99,3,2,1])

In [21]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [22]:
a,b,c = np.split(x,[3,5]) #Birbirinden ayrilan degerler virgüllerle ayrilmis degiskenlere atanabilir

In [23]:
a

array([1, 2, 3])

In [24]:
b

array([99, 99])

In [25]:
c

array([3, 2, 1])

### Iki Boyutlu Ayirma (vsplit , hsplit)

In [28]:
import numpy as np

array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
a,b = np.vsplit(array , [2]) # vstrip satirdan bolmek icin kullanilir

In [31]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
a,b = np.hsplit(array, [2]) #hsplit sutundan bolmek icin kullanilir

In [35]:
a

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [36]:
b

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## Sorting (Siralama)

In [39]:
import numpy as np

In [42]:
array = np.random.normal(20,5,(3,3))
array

array([[18.02257713, 18.34546599, 25.49070545],
       [16.00204647, 17.58358942, 18.11655205],
       [16.79472525, 14.3415914 , 20.51698124]])

In [48]:
array_sorted = np.sort(array)
array_sorted

array([[18.02257713, 18.34546599, 25.49070545],
       [16.00204647, 17.58358942, 18.11655205],
       [14.3415914 , 16.79472525, 20.51698124]])

In [50]:
array_sorted = np.sort(array , axis=0)
array_sorted

array([[14.3415914 , 16.79472525, 18.11655205],
       [16.00204647, 17.58358942, 20.51698124],
       [18.02257713, 18.34546599, 25.49070545]])

## Index ile Elemanlara erismek

In [1]:
import numpy as np

In [4]:
array = np.random.randint(10 , size= 10)
array

array([2, 5, 7, 6, 3, 4, 3, 7, 5, 9])

In [5]:
array[0] # arrayin 0. indexine erismek

2

In [6]:
array[3]

6

## Slicing ile Array'in alt kumesine erismek

In [10]:
array2dim = np.random.randint(20 , size = (4,5))
array2dim

array([[12,  9, 18,  1, 15],
       [15, 11, 12, 18, 11],
       [18,  2,  8, 10,  2],
       [ 6, 17,  2,  1, 15]])

In [11]:
array2dim[2,2]

8

In [15]:
array2dim[:3,:2]

array([[12,  9],
       [15, 11],
       [18,  2]])

In [16]:
array2dim[2,:]

array([18,  2,  8, 10,  2])

In [17]:
array2dim[:,3]

array([ 1, 18, 10,  1])

In [32]:
array2dim

array([[12,  9, 18,  1, 15],
       [15, 11, 12, 18, 11],
       [18,  2,  8, 10,  2],
       [ 6, 17,  2,  1, 15]])

## Fancy Ile Erismek 

In [59]:
import numpy as np
array = np.random.randint(10,size=10)
array

array([0, 7, 2, 3, 6, 1, 3, 0, 1, 0])

In [60]:
fancyindex = [1,4,6]
array[fancyindex]

array([7, 6, 3])

In [79]:
array2dim = np.random.randint(9, size = (3,3))
array2dim

array([[4, 7, 7],
       [4, 7, 7],
       [1, 4, 8]])

In [80]:
fancy2dim = np.array([0,2])
fancy2dim_2 = np.array([0,2])

array2dim[fancy2dim,fancy2dim_2]

array([4, 8])

#### Slice ile Fnacy

In [81]:
array2dim[0:,[0,1]]

array([[4, 7],
       [4, 7],
       [1, 4]])

## Conditional element operations (Kosullu Eleman Islemleri)

In [83]:
import numpy as np

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
array < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [87]:
array[array<5]

array([0, 1, 2, 3, 4])

In [88]:
array[array>7]

array([8, 9])

In [90]:
array[array != 2]

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

## Mathematical operations (Matematiksel Islemler)

In [92]:
import numpy as np

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.subtract(array,1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [96]:
np.add(array,3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
np.multiply(array,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
np.divide(array,3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [99]:
np.power(array,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [100]:
np.mod(array,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [101]:
np.absolute(np.array([-1,-2,-3]))

array([1, 2, 3])

In [102]:
np.sin(360)

0.9589157234143065

In [105]:
np.cos(180)

-0.5984600690578581

In [106]:
array = [1,2,3]
np.log(array)

array([0.        , 0.69314718, 1.09861229])

In [107]:
np.log2(array)

array([0.       , 1.       , 1.5849625])

In [108]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125])

## Equation with two unknowns (Iki Bilinmeyenli denklem)

* **2 * x0 + 2 * x1 = 20**
* **x0 + 4 * x2 = 24**

In [111]:
a = np.array([[2,2],[1,4]])
b = np.array([20,24])
solution = np.linalg.solve(a,b)
solution

array([5.33333333, 4.66666667])