# Data Manuplation Numpy & Pandas

In [1]:

import numpy as np

newarray = np.array([1,2,3,4,5])
newarray

array([1, 2, 3, 4, 5])

In [2]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a*b

array([ 2,  6, 12])

In [3]:
type(newarray)

numpy.ndarray

In [4]:
np.zeros(10,dtype=int) # dtype elemanlarin turunu belirtmek icin kullanilir

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

## Creating Numpy Array

In [10]:
np.arange(0,30,3) # tek boyutlu dizi olusturma (0 dan 30 a kadar 3 er artan)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
np.linspace(0,1,10) # Iki deger araliginda sayilar olusturur (0 ve 1 arasinda 10 sayi olusturur)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.random.normal(10,4,(3,4)) # Normal dagilima uygun array olusturur (ort: 10 , standart sapma:4 , 3 e 4 luk array)

array([[ 5.16434831,  6.14183365,  5.70608295, 13.81593401],
       [ 4.46998833, 11.50472788, 12.79196008, 10.76254271],
       [ 9.74672896, 15.41925395,  5.72361236, 11.55951131]])

In [13]:
np.random.randint(0,10,(3,3)) # rastgele int ler olusturmak (0 dan 10 a kadar 3'e 3 luk)

array([[7, 7, 8],
       [3, 1, 8],
       [1, 4, 4]])